server:
  port: 8082

spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:postgresql://postgres-blog:5432/blog_db
    # url: jdbc:postgresql://localhost:54321/auth_db   
    username: blog_user
    password: blog_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/

jwt:
  secret: bGkOZnNlT5JzV3lJpMmBpjC+HggdZvlYPFbdS70ypWo=
  expiration: 3600000         
  refresh-expiration: 604800000
