server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
        defaultZone: http://discovery:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
